services:

  mysql:
    image: mysql:8.0
    container_name: ecommerce-mysql

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: product_db

    volumes:
      - mysql_data:/var/lib/mysql

    networks:
      - ecommerce-network

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  product-service:
    build: ./product-service
    container_name: product-service

    ports:
      - "8082:8082"

    depends_on:
      mysql:
        condition: service_healthy

    networks:
      - ecommerce-network

  auth-service:
    build: ./auth-service
    container_name: auth-service

    ports:
      - "8081:8081"

    depends_on:
      mysql:
        condition: service_healthy

    networks:
      - ecommerce-network

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway

    ports:
      - "8080:8080"

    depends_on:
      - auth-service
      - product-service

    networks:
      - ecommerce-network

networks:
  ecommerce-network:

volumes:
  mysql_data: